-- SUPERSEDED. The dashboard now uses Supabase Auth + Postgres + RLS.
--
--   Current schema:  database/migrations/0001_init.sql
--   Example seed:     database/seed.example.sql
--
-- This file described the pre-Supabase data model (customers / app_users with
-- password_hash / audit_log, no RLS) that went with env-var login. It is kept
-- only for history; do not apply it to a new project.
